services:
  mysql-buscador:
    image: mysql:8.0
    container_name: mysql-buscador
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buscador
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - mysql-buscador-data:/var/lib/mysql

  mysql-operador:
    image: mysql:8.0
    container_name: mysql-operador
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operador
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - mysql-operador-data:/var/lib/mysql

volumes:
  mysql-buscador-data:
  mysql-operador-data: